# Making an X Matrix of the Mel-Spectrogramm of the audio

In [1]:
import sys
import os
import numpy as np
import pandas as pd
import pickle
import matplotlib as plt
import matplotlib.pyplot as plt
sys.path.append(os.path.abspath("../lingpred_audio/"))
from audio import word_avg_sg, get_words_onsets_offsets

In [2]:
# define the data set and number of mels
dataset               = 'Goldstein'
mels                  = 8
use_real_word_offsets = True

In [10]:
if dataset== 'Goldstein':
    acoustic_model = word_avg_sg(subject=1, session=1, n_mels=8, dataset = dataset,task = 1, use_real_word_offsets=use_real_word_offsets) 
# otherwise we will have to loop over sessions (Armeni) or tasks (Gwilliams)
# see code two cells down

0

In [11]:
acoustic_model.shape

(5136, 9)

In [12]:
# save
if dataset == 'Goldstein':

    audio_dir = '../audio/'

    if use_real_word_offsets:
        filename  = audio_dir+'{}/acoustic_model_{}_mels_averaged_per_word_using_word_offsets.pkl'.format(dataset, mels)
    else:
        filename  = audio_dir+'{}/acoustic_model_{}_mels_averaged_per_word_using_next_word_onset_as_offset.pkl'.format(dataset, mels)
    
    f = open(filename,"wb")
    pickle.dump(acoustic_model,f)
    f.close()

## For the Armeni & Gwilliams datasets there are several sessions over which we must loop

In [ ]:
subject  = 1
#task     = 0  # uncomment for running for Armeni dataset
session = 0 # uncomment for running for Gwilliams dataset

tasks    = ['0', '1', '2', '3']
sessions = [1]
mels     = [8]
dataset  = 'Gwilliams' #"Armeni"
audio_dir = '../audio/'


# for the Gwilliams dataset we loop over tasks || for the Armani over sessions
for mel in mels:
    
    acoustic_model = np.empty(shape=(0, mel+1))
    
    for task in tasks: 
    #for session in sessions: # uncomment for running for Armeni dataset
        
        if subject == 3 and dataset == 'Armani':
            if session == 8:
                continue
        
        avg_spec_init_phone = word_avg_sg(subject=subject, session=session, 
                                                  n_mels=mel, dataset = dataset,
                                                  task = task)
        print(avg_spec_init_phone.shape)
        acoustic_model = np.vstack([acoustic_model, avg_spec_init_phone])

    if use_real_word_offsets:
        filename  = audio_dir+'{}/acoustic_model_{}_mels_averaged_per_word_using_word_offsets.pkl'.format(dataset, *mels)
    else:
        filename  = audio_dir+'{}/acoustic_model_{}_mels_averaged_per_word_using_next_word_onset_as_offset.pkl'.format(dataset, *mels)

    f = open(filename,"wb")
    pickle.dump(acoustic_model,f)
    f.close()

0

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

1

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

2

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

3

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

(613, 9)
0

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

1

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

2

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

3

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

4

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

5

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

(1383, 9)
0

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

1

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

2

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

3

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

4

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

5

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

6

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

7

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

(2359, 9)
0

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

1

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

2

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

3

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

4

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

5

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

6

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

7

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

8

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

9

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

10

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

11

/Users/ines/research/Lingpred/lingpred_audio/audio.py:489: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words.rename(columns={'start': 'onset'}, inplace=True)
/Users/ines/research/Lingpred/lingpred_audio/audio.py:493: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_words['offset'] = offsets

(3390, 9)

NameError: name 'audio_dir' is not defined

### ... checking some word off sets and onsets ... for control

In [12]:
df = get_words_onsets_offsets(dataset=dataset, subject=1, session=1, run=1, task='0', use_real_word_offsets=False)
df

,onset,duration,sample,type,value,offset
3,1.089189,0.129705,46637.372038,word_onset_01,THE,1.213895
6,1.218895,0.678458,46793.018296,word_onset_01,ADVENTURES,1.892353
15,1.897353,0.089796,47607.167956,word_onset_01,OF,1.982149
18,1.987149,0.488889,47714.923058,word_onset_01,SHERLOCK,2.471037
24,2.476037,0.698413,48301.589725,word_onset_01,HOLMES,3.907772
...,...,...,...,...,...,...
6101,473.884654,0.209524,613991.929861,word_onset_01,SAID,474.089178
6105,474.094178,0.249433,614243.358433,word_onset_01,HE,475.027046
6110,475.032046,0.269388,615368.800610,word_onset_01,READ,475.296434
6114,475.301434,0.129705,615692.065916,word_onset_01,IT,475.426139
6117,475.431139,0.568707,615847.712174,word_onset_01,ALOUD,475.999847

In [35]:
#diff = df.offset - df.end
#print(diff.mean(), diff.min(), diff.argmin())
#df.iloc[1660:1680]

0.11298410720582895 -2.783900000000017 1669

         word       onset      offset  new_offset
1660       by  566.969828  567.139828  567.174828
1661        a  567.179828  567.209828  567.304828
1662   monkey  567.309828  567.739828  568.134828
1663     Yeah  568.139828  568.359828  568.694828
1664     just  568.699828  568.829828  568.924828
1665       as  568.929828  568.979828  569.014828
1666        I  569.019828  569.129828  569.224828
1667     just  569.229828  569.399828  569.934828
1668     yeah  569.939828  570.089828  570.694828
1669     Yeah  570.699828  570.839828  568.055928
1670      You  568.060928  568.120928  568.155928
1671    found  568.160928  568.340928  568.395928
1672      out  568.400928  568.530928  568.545928
1673      the  568.550928  568.610928  568.665928
1674   monkey  568.670928  568.940928  568.955928
1675      was  568.960928  569.130928  569.185928
1676    suing  569.190928  569.450928  569.485928
1677      you  569.490928  569.760928  569.955928
1678  because  569.960928  570.240928  570.295928
1679     your  570.300928  570.390928  570.425928

### Ok, this is happening because they are talking over one another here.